### ISSUE TITLE
How to use loyalty with different records

### ISSUE THREAD

**Issue by tkawa** [kyuden/banken#1]
I call `loyalty` multiple times with different records, then I seem to get the same loyalty instance.
What should I do to use different loyalties for each record?

https://github.com/kyuden/banken/blob/master/lib/banken.rb#L50

``` ruby
  def loyalty(record=nil, controller_name=nil)
    controller_name = banken_controller_name unless controller_name
    loyalties[controller_name.to_s] ||= Banken.loyalty!(controller_name, banken_user, record)
  end
```

**Comment by kyuden** [comment]
@tkawa 

Loyalty and Controller is one-to-one pair not Model. So, Records don't associate to Loyalty.

For example, If you want to authorize `ArticlesController#update`, you only have to define requirement of authorization in `ArticlesLoyalty#update?` which has same name as `ArticlesController` without thinking about what to use record in `ArticlesController#update`. 

> What should I do to use different loyalties for each record?

So, You should call `loyalty` each Controller not record.

## 

If only it need to record for requirement of authorization in `ArticlesLoyalty#update?`, You can pass record to first argument in `authorize!`.

``` ruby
class ArticlesController < ApplicationController
  before_action :set_article

  def update
    authorize! @article


```

`record` is `@article` of passing to first argument in `authorize!`.
`user` is `current_user` on Controller like `ApplicationController`.

``` ruby
class ArticlesLoyalty < ApplicationLoyalty
  def update?
    user.admin? || record.user_id == user.id
  end

```

## 

If you don't need to record for requirement of authorization in `ArticlesLoyalty#update?`, You don't need to pass record to first argument in `authorize!`. Because Loyalty and Controller is one-to-one pair of same name base not Model.

``` ruby
class ArticlesController < ApplicationController
  before_action :set_article

  def update
    authorize!


```

``` ruby
class ArticlesLoyalty < ApplicationLoyalty
  def update?
    user.admin?
  end

```

**Comment by tkawa** [comment]
I probably get the point.
How about this code that appears in a view?

``` erb
<% @posts.each do |post| %>
  <% if loyalty(post, :posts).update? %>
    <%= link_to "Edit post", edit_post_path(post) %>
  <% end %>
<% end %>
```

(This is based on the example in README.md)

**Comment by kyuden** [comment]
@tkawa 
I misunderstood. You talk about view helper, don't you.
It can't dynamically swith loyalty by record(model). Because, Loyalty and Controller is one-to-one pair not Model. But, You can statically call different loyalty by passing name of loyalty to second argument in `loyalty`.

``` ruby
# call PostsLoyalty#update? 
loyalty(post, :posts).update?
```

``` ruby
# call UsersLoyalty#update? 
loyalty(post, :users).update?
```

Essentially, I think switched content is different each loyalty if it need to use different loyalties. What I've meant is that `<%= link_to "Edit post", edit_post_path(post) %>`(switched content) should be authorized by same loyalty. So, If loyalty is different, Also different content. and You can statically call different loyalty each  switched content.

``` erb
<% @posts.each do |post| %>
  # call PostsLoyalty$update?
  <% if loyalty(post, :posts).update? %>
    <%= link_to "Edit post", edit_post_path(post) %>
  <% end %>

  # call UsersLoyalty$update?
  <% if loyalty(post.user, :users).update? %>
    <%= link_to "Edit user", edit_user_path(post.user) %>
  <% end %>
<% end %>
```

So, I don't think it need to swith loyalty by record(model) dynamically.

**Comment by tkawa** [comment]
Take a look at this issue page. You can edit only comments you posted, so you should see an edit button in upper right corner of only your comments. This page is definitely one of the examples.

``` erb
<% @issue.comments.each do |comment| %>
  <%= comment.user.name %> commented <%= time_ago_in_words(comment.created_at) %>
  <% if loyalty(comment, :comments).update? %>
    <%= link_to "Edit comment", edit_comment_path(comment) %>
  <% end %>
  <%= comment.body %>
<% end %>
```

**Comment by kyuden** [comment]
`loyalty` get the same loyalty instance each record as you said.
This is bug. So, I fixed it. https://github.com/kyuden/banken/commit/a484f8f3a00773c295f93199a0c80ff3e74403f7

And Tagged 1.0.2

thx! @tkawa

**Comment by tkawa** [comment]
Thanks!
